### ISSUE TITLE
macOS usage

### ISSUE THREAD

**Issue by chammaaomar** [MauriceGit/compiler#1]
First of all, really cool project! I'd love to try it out, but I can't seem to get it to work. So I did
```shell
go build
brew install yasm
./compiler test.lang
```

I've taken a look a `test.lang`, and I assume it's the example source file. Then I get the following error:

```shell
ld: warning: No version-min specified on command line
ld: warning: -arch not specified
ld: warning: -macosx_version_min not specified, assuming 10.11
ld: warning: ignoring file /var/folders/5p/9qqn9bds0kxf85ctpy0s12bm0000gn/T/061022517, file was built for unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): /var/folders/5p/9qqn9bds0kxf85ctpy0s12bm0000gn/T/061022517
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for inferred architecture x86_64
Error while linking object file - exit status 1
```

Maybe I'm supposed to be linking something, like in C it would be, e.g. `gcc -lcurl ...`, but I'm not sure. Thanks for the help!

**Comment by guitmz** [comment]
generated code is for Linux only (ELF file), assembly is very strict about architecture and operating system and this tool seems to aim only at Linux at this moment

**Comment by chammaaomar** [comment]
Ok that's good to know. Thanks! I'll be running it inside a Docker container then.

**Comment by MauriceGit** [comment]
Hey,

that is correct (Linux ELF executable only). I didn't really consider system independence and probably won't.

If you run into some more problems or issues with the compiler/language, please let me know!
Have fun :)
