### ISSUE TITLE
return analysis is a bit naive

### ISSUE THREAD

**Issue by zagortenay333** [MauriceGit/compiler#2]
Error should be emitted but isn't:
```
fun test () int {
    for ;; {
        break
        return 0
    }    
}
```
Error emitted but shouldn't be:
```
fun test (x int) int {
    if x == 0 { return 0 } else { }

    if x == 0 { return 0 } else { return 0 }
}
```

**Comment by MauriceGit** [comment]
You're right, thanks!

I didn't review it after adding break/continue and forgot about your second example. Thanks for providing it! Will fix it next week.

**Comment by MauriceGit** [comment]
Rewrote return analysis.

Fix: At least one statement in a function must return from all possible paths (with a block being a statement). Break and Continue will return false, only a Return will be true.

Anything I missed? (No constant evaluation during compile-time or compile-time check for constant boolean expressions yet.)

**Comment by zagortenay333** [comment]
Why say false on things like assignment?
https://github.com/MauriceGit/compiler/blob/3acc80cafb12d614f6b2b1ea586ac1723742dbe7/functionReturnAnalysis.go#L27-L32

Also, why are you not examining the switch cases?

**Comment by MauriceGit** [comment]
I kind-of forgot the switch statement here. I'll add that.

Go doesn't have a default fall-through (So I don't return false here. There is a ```fallthrough``` statement in Go for that). I still list it in the switch to enable the panic in the default case. This is done so that I don't forgot to add potential special handling here when I add a new Statement type in the compiler.

**Comment by zagortenay333** [comment]
Ah, ok.

**Comment by MauriceGit** [comment]
Update:
Fixed the switch statement return analysis. And removed the recursive call for loop bodies, as we cannot guarantee, that a loop body is executed at least once. So no guaranteed return is possible here.
